---
title: "ENEM 2019"
author: "Grupo - Educação"
date: "03/02/2022"
output: pdf_document
---

```{r bibliotecas, include=FALSE}
library(tidyverse)
library(data.table)
library(curl)
```

```{r importação de dados}
# Alocação de memória no R
memory.limit(memory.limit()*2)

# Importando a base
ENEM_2019 <- data.table::fread(input='MICRODADOS_ENEM_2019.csv',
                               integer64='character',
                               skip=0,  #Ler do inicio
                               nrow=-1, #Ler todos os registros
                               na.strings = "", 
                               showProgress = TRUE)

# Observar nome das variáveis
list(names(ENEM_2019))
```

```{r tratamento de dados}
ENEM_2019_clean <- ENEM_2019 %>%
  filter(
    duplicated(NU_INSCRICAO) == F, # Eliminando duplicatas
    TP_PRESENCA_CN == 1,           # Presente em CN 
    TP_PRESENCA_CH == 1,           # Presente em CH
    TP_PRESENCA_LC == 1,           # Presente em LC
    TP_PRESENCA_MT == 1,           # Presente em MT
    TP_STATUS_REDACAO != 2,        # Não teve a redação anulada
    TP_ST_CONCLUSAO == 2,          # Esta cursando e irá terminar o EM em 2019
    IN_TREINEIRO ==0,              # Removendo treineiros
    is.na(CO_ESCOLA) == F          # Somente escolas com código no Censo Escolar
    ) %>%    
  select(-c(3:6,     # Residência (participante)
            9,11:16, # Estado civil e nascimento (participante)
            20, 29:79, # Condições especiais + treineiro
            80:91,    # Local da prova, cor e participação
            96:104,   # Gabarito e respostas
            105:110,  # Referente à redação
            112:136)  # Referente ao questionário socioeconômico
         )

list(names(ENEM_2019_clean))

write.csv(ENEM_2019_clean, file = "enem_2019_censo_escolar.csv")
```

```{r média por escola censo escolar}
# Importando base de dados do github
## Amigos recomendo vocês importarem direto essa go git hub porque é bem mais leve
df.enem_2019 <- read.csv(curl::curl("https://github.com/ocesarfreitas/Laboratorio-Econometria/blob/main/ENEM/2019/enem_2019_censo_escolar.csv?raw=true"))

# Observando a estrutura
str(df.enem_2019)

# Calculando a média por escola
df.enem.clean_2019 <- df.enem_2019 %>%
  select(CO_ESCOLA, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT,
         NU_NOTA_REDACAO) %>%
  group_by(CO_ESCOLA) %>%
  mutate_at(2:6, as.numeric) %>%
  summarise_at(vars(NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT,
                    NU_NOTA_REDACAO), list(mean = mean))

# Selecionando as escolas com pelo menos 10 participantes
## Obs. Deve ter um jeito mais fácil de fazer isso mas tava com preguiça
df.enem.ma10.2019 <- df.enem_2019 %>%
  group_by(CO_ESCOLA) %>%
  summarise(n=n()) %>%
  filter(n >= 10) %>%
  select(-n)

# Captando as escolas que atendem os requsitos 
df.enem.2019.final <- right_join(df.enem.clean_2019, df.enem.ma10.2019,
                                by = "CO_ESCOLA")
```

